services:
  gitea_app:
    image: gitea/gitea:${GITEA_VERSION:-latest}
    container_name: gitea_app
    restart: unless-stopped
    depends_on:
      - gitea_postgres
    ports:
      - 3000:3000 #so the instance can be accessed without the use of cloudflare tunnel in the LAN
      - 2222:22
    environment:
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=gitea_postgres:5432
      - GITEA__database__NAME=${POSTGRES_DB}
      - GITEA__database__USER=${POSTGRES_USER}
      - GITEA__database__PASSWD=${POSTGRES_PASSWORD}
    volumes:
      - ${GITEA_DATA_VOLUME}:/data
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    networks:
      - gitea
      - proxy

  gitea_postgres:
    image: postgres:18-alpine
    container_name: gitea_postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ${GITEA_DB_VOLUME}:/var/lib/postgresql/data
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    networks:
      - gitea

networks:
  gitea:
    name: gitea_network
    driver: bridge
  proxy:
    name: proxy_network
    external: true
